### ISSUE TITLE
PPS "train" return code: 126

### ISSUE THREAD

**Issue by ohmiya** [algbioi/ppsplus#1]
Hello,

When running ppsplus to analyze our own data, I ran into the following error.

PPS "train" return code: 126
Traceback (most recent call last):
  File "/apps/pps/tools/pps/tools/ppsplus/algbioi/core/run.py", line 1008, in <module>
    main()
  File "/apps/pps/tools/pps/tools/ppsplus/algbioi/core/run.py", line 510, in main
    raise Exception("PPS train returned with non-zero %s status: %s" % (trainProc.returncode, trainCmd))
Exception: PPS train returned with non-zero 126 status: /apps/pps/tools/pps/tools/PhyloPythiaS/1_3/scripts/train.rb /home/work/PPS_config_generated.txt

We set a contig file assembled by metaSPAdes, but we don't use a scaffold file.
Reference files are set as follows:
databaseFile=/mnt/host_shared/reference_NCBI201502/taxonomy
refSeq=/mnt/host_shared/reference_NCBI201502/centroids_noplasmids
s16Database=/mnt/host_shared/reference_NCBI201502/silva115
mgDatabase=/mnt/host_shared/reference_NCBI201502/mg5

Thank you for you help.

**Comment by algbioi** [comment]
Thank you for using PPS+. Could you please check that all the paths in the configuration file are valid paths and that you have the correct permissions? Also that you have enough disk space? And, the shared folder is mounted properly? Error 126 is related to incorrect permissions.

**Comment by ohmiya** [comment]
As you pointed out, my ruby was installed at /usr/local/bin/ruby, while the script train.rb looks for it at /usr/bin/ruby. Thank you so much! Right now the script works.
